name: "Unit tests"

inputs:
  test-name:
    description: 'Unit test name'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        path: repo
    - name: Trigger unit tests
      run: |
        echo "Attempting to run unit tests"
        cd repo/src
        sudo tox -e ${{ inputs.test-name }}
        exit_code=$?
        echo "Unit tests finished"
        exit $exit_code
      shell: bash
    - name: Clean up virtualenv
      run: |
        sudo rm -rf .tox/${{ inputs.test-name }}
      shell: bash
