name: "Unit tests"

inputs:
  test-name:
    description: 'Unit test name'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Run unit tests
      env:
        TEST_NAME: ${{ inputs.test-name }}
      run: |
        cd src
        mkdir -p ".tox/${TEST_NAME}/log"
        tox run -e "${TEST_NAME}"
      shell: bash
