# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# Default values for gmc.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

proxy:
  httpProxy: ""
  httpsProxy: ""
  noProxy: ""

tokens:
  hugToken: ""


# Common tag & repository for all images. Override if needed for specific images.
common_tag: &tag "latest"
common_repository: &repo "localhost:5000"

images:
  gmcManager:
    image: "opea/gmcmanager"
    repository: *repo
    tag: *tag
    pullPolicy: Always
  gmcRouter:
    image: "opea/gmcrouter"
    repository: *repo
    tag: *tag
  dataprep-usvc:
    image: "opea/dataprep"
    repository: *repo
    tag: *tag
  embedding-usvc:
    image: "opea/embedding"
    repository: *repo
    tag: *tag
  reranking-usvc:
    image: "opea/reranking"
    repository: *repo
    tag: *tag
  torchserve:
    image: "opea/torchserve"
    repository: *repo
    tag: *tag
  retriever-usvc:
    image: "opea/retriever"
    repository: *repo
    tag: *tag
  ingestion-usvc:
    image: "opea/ingestion"
    repository: *repo
    tag: *tag
  llm-usvc:
    image: "opea/llm"
    repository: *repo
    tag: *tag
  in-guard-usvc:
    image: "opea/in-guard"
    repository: *repo
    tag: *tag
  out-guard-usvc:
    image: "opea/out-guard"
    repository: *repo
    tag: *tag
  ui-usvc:
    image: "opea/chatqna-conversation-ui"
    repository: *repo
    tag: *tag


imagePullSecrets:
  - name: regcred
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}
podLabels:
  control-plane: gmc-controller

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  runAsNonRoot: true
  allowPrivilegeEscalation: false

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

livenessProbe:
  httpGet:
    path: /healthz
    port: gmc
  initialDelaySeconds: 15
  periodSeconds: 20
readinessProbe:
  httpGet:
    path: /readyz
    port: gmc
  initialDelaySeconds: 5
  periodSeconds: 10

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}
