# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# Default values for gmc.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

proxy:
  httpProxy: ""
  httpsProxy: ""
  noProxy: ""


tokens:
  hugToken: ""

images:
  gmcManager:
    repository: "localhost:5000/opea/gmcmanager"
    tag: "latest"
    pullPolicy: Always
  gmcRouter:
    repository: "localhost:5000/opea/gmcrouter"
    tag: "latest"
  dataprep-usvc:
    repository: "localhost:5000/test/dataprep"
    tag: "latest"
  embedding-usvc:
    repository: "localhost:5000/opea/embedding-tei"
    tag: "latest"
  reranking-usvc:
    repository: "localhost:5000/opea/reranking"
    tag: "latest"
  torcheserve:
    repository: "localhost:5000/pl-qna-rag-embedding-torchserve"
    tag: "latest"
  retriever-usvc:
    repository: "localhost:5000/test/retriever"
    tag: "latest"
  ingestion-usvc:
    repository: "localhost:5000/test/ingestion"
    tag: "latest"
  llm-uservice:
    repository: "localhost:5000/opea/llm"
    tag: "latest"




imagePullSecrets:
  - name: regcred
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}
podLabels:
  control-plane: gmc-controller

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  runAsNonRoot: true
  allowPrivilegeEscalation: false

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

livenessProbe:
  httpGet:
    path: /healthz
    port: gmc
  initialDelaySeconds: 15
  periodSeconds: 20
readinessProbe:
  httpGet:
    path: /readyz
    port: gmc
  initialDelaySeconds: 5
  periodSeconds: 10

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}
