# Copyright (C) 2024-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
- name: "app_watcher | Scale is not applicable"
  ansible.builtin.debug:
    msg: "Watcher CronJob does not support scaling"
