{{- if .Values.monitoring.enabled }}
# Copyright (C) 2024-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "nats.fullname" . }}
  labels:
    {{- include "nats.labels" . | nindent 4 }}
    release: {{ .Release.Name }}
spec:
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "nats.selectorLabels" . | nindent 6 }}
      nats.io/service: client
  endpoints:
  - port: metrics
{{- end }}
