{{- if index .Values "otelcol-traces" "enabled" }}
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otelcol-traces
  namespace: monitoring # this and namespace below is required because Prometheus only watches in monitoring tagged with release
  labels:
    release: telemetry  # see above
spec:
  namespaceSelector:
    matchNames:
    - monitoring-traces
  selector:
    matchLabels:
      app.kubernetes.io/component: opentelemetry-collector
      app.kubernetes.io/instance: monitoring-traces.otelcol-traces
      app.kubernetes.io/name: otelcol-traces-collector-monitoring
  endpoints:
  - port: "monitoring"
{{- end}}
