# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

version: '3.8'

services:
  embedding-tei-model-server:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.5
    container_name: embedding-tei-model-server
    ports:
      - "${PORT}:80"
    volumes:
      - ./data:/data
    environment:
      - NO_PROXY=${NO_PROXY}
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
    command: ["--model-id", "${MODEL_NAME}"]
    runtime: runc
    ipc: host

  embedding_usvc:
    build:
      context: ../../../../../../
      dockerfile: ./comps/embeddings/impl/microservice/Dockerfile
      target: ${FRAMEWORK}
    container_name: embedding-tei-microservice
    environment:
      - NO_PROXY=${NO_PROXY}
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
      - FRAMEWORK=${FRAMEWORK}
      - EMBEDDING_MODEL_NAME=${PARSED_MODEL_NAME}
      - EMBEDDING_MODEL_SERVER=tei
      - EMBEDDING_MODEL_SERVER_ENDPOINT=http://localhost:${PORT}
    ipc: host
    runtime: runc
    network_mode: host
    restart: unless-stopped
    depends_on:
      - embedding-tei-model-server
