# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: habana-exporter
  labels:
    release: rag-telemetry
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: habana-metric-exporter-ds
  podMetricsEndpoints:
  - port: habana-metrics



