apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-exporter
  labels:
    release: rag-telemetry
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-redis-exporter
  endpoints:
  - port: "redis-exporter"
