# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

version: "3.8"

services:
  reranking-tei-model-server:
    # todo: check why tag cpu-1.5 does not work with reranking
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.2
    container_name: reranking-tei-model-server
    ports:
      - "${RERANKER_TEI_PORT}:80"
    volumes:
      - ./data:/data
    environment:
      - NO_PROXY=${NO_PROXY}
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
    command: ["--model-id", "${RERANKER_TEI_MODEL_NAME}"]
    runtime: runc
    ipc: host
  reranking_usvc:
    build:
      context: ../../../../../../
      dockerfile: ./comps/reranks/impl/microservice/Dockerfile
    container_name: reranking-tei-microservice
    ipc: host
    runtime: runc
    network_mode: host
    environment:
      - NO_PROXY=${NO_PROXY}
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
      - HF_TOKEN=${HUGGINGFACE_API_KEY}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - RERANKING_SERVICE_URL=http://localhost:${RERANKER_TEI_PORT}/rerank
      # Pass the environment variable if it is provided in .env file;
      # otherwise, use the defaults specified in reranks/config.ini
      - RERANKING_HOST:= ${RERANKING_HOST:-}
      - RERANKING_PORT:= ${RERANKING_PORT:-}
      - RERANKING_NAME:= ${RERANKING_NAME:-}
      - RERANKIG_LOG_LEVEL:= ${RERANKIG_LOG_LEVEL:-}
      - RERANKING_LOG_PATH:= ${RERANKING_LOG_PATH:-}
    restart: unless-stopped
    depends_on:
      - reranking-tei-model-server
