# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: router-service
  labels:
    release: rag-telemetry
spec:
  namespaceSelector:
    matchNames:
    - chatqa
  selector:
    matchLabels:
      app: router-service
  podMetricsEndpoints:
  - targetPort: 8080



