apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tgi-service-m
  labels:
    release: rag-telemetry
spec:
  namespaceSelector:
    matchNames:
    - chatqa
  selector:
    matchLabels:
      app.kubernetes.io/instance: tgi
  endpoints:
  - port: "tgi"
