FROM language-detection-base:latest

COPY compliance /compliance

WORKDIR /compliance/ospdt
COPY Dockerfile .
COPY uv.lock .

# CMD from base Dockerfile
WORKDIR /home/user/comps/language_detection
CMD ["python", "erag_language_detection_microservice.py"]
