{
 "title": "EnterpriseRAG / HPA",
 "tags": [
  "entrag",
  "hpa"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "hpa",
    "label": "Horizontal Pod Autoscaler(s)",
    "query": {
     "query": "label_values(kube_horizontalpodautoscaler_info{horizontalpodautoscaler!=\"istiod\"},horizontalpodautoscaler)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Current Replicas",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_status_current_replicas{horizontalpodautoscaler=~\"$hpa\"}",
     "legendFormat": "{{horizontalpodautoscaler}}"
    }
   ]
  },
  { "title": "$hpa", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }, "repeat": "hpa" },
  {
   "title": "Replicas ($hpa)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_spec_min_replicas{horizontalpodautoscaler=~\"$hpa\"}",
     "legendFormat": "min"
    },
    {
     "expr": "kube_horizontalpodautoscaler_spec_max_replicas{horizontalpodautoscaler=~\"$hpa\"}",
     "legendFormat": "max"
    },
    {
     "expr": "kube_horizontalpodautoscaler_status_desired_replicas{horizontalpodautoscaler=~\"$hpa\"}",
     "legendFormat": "desired_replicas"
    },
    {
     "expr": "kube_horizontalpodautoscaler_status_current_replicas{horizontalpodautoscaler=~\"$hpa\"}",
     "legendFormat": "current_replicas"
    }
   ]
  },
  {
   "title": "Metric Current Value vs Scaling Threshold",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum by(metric_name)(kube_horizontalpodautoscaler_status_target_metric{horizontalpodautoscaler=~\"$hpa\", service=\"kube-prometheus-stack-kube-state-metrics\"})",
     "legendFormat": "current_{{metric_name}}"
    },
    {
     "expr": "sum by(metric_name)(kube_horizontalpodautoscaler_spec_target_metric{horizontalpodautoscaler=~\"$hpa\", service=\"kube-prometheus-stack-kube-state-metrics\"})",
     "legendFormat": "threshold_{{metric_name}}"
    }
   ]
  }
 ]
}