{
 "title": "EnterpriseRAG / Services / GMConnector (router)",
 "description": "Spanmetrics way of demo application view.",
 "tags": [
  "entrag",
  "microservices"
 ],
 "time": { "from": "now-30m", "to": "now-1m" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "http_route",
    "label": "Route (as Server)",
    "query": {
     "query": "label_values(http_server_duration_milliseconds_count,http_route)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_service_created{namespace=~\"chatqna|edp|docsum\"},namespace)"
    }
   },
   {
    "name": "service",
    "label": "Service (as Client)",
    "query": {
     "query": "label_values(http_client_duration_milliseconds_count{namespace=~\"$namespace\"},net_peer_name)"
    }
   },
   {
    "name": "percentile",
    "label": "Percentile",
    "query": "0.50, 0.95, 0.99, 0.999, 0.9999, 0.99999"
   },
   {
    "name": "http_status_code",
    "label": "HTTP status code",
    "query": {
     "query": "label_values(http_server_duration_milliseconds_count,http_status_code)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP Client services - Throughput and Latencies (filter by \"Service\")",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Client latencies requests histogram for \"${service}\"",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "repeat": "service",
   "targets": [
    {
     "expr": "sum(increase( http_client_duration_milliseconds_bucket{net_peer_name=~\"$service\", namespace=\"$namespace\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 3x3 - Service Latency - percentile$percentile",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum(rate(http_client_duration_milliseconds_bucket{net_peer_name=~\"$service\", namespace=\"$namespace\"}[$__rate_interval])) by (le,net_peer_name))",
     "legendFormat": "{{net_peer_name}}"
    }
   ]
  },
  {
   "title": "Top 7 Services Mean Rate over Range",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(7,sum by (net_peer_name) (rate(http_client_duration_milliseconds_count{net_peer_name=~\"$service\", namespace=\"$namespace\"}[$__range])))",
     "legendFormat": "{{net_peer_name}}"
    }
   ]
  },
  {
   "title": "Top 7 Router Client Latencies Over Range  (status=200 only) by service",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "increase(http_client_duration_milliseconds_sum{net_peer_name=~\"$service\", http_status_code=\"200\", namespace=\"$namespace\"}[$__rate_interval]) / increase(http_client_duration_milliseconds_count{net_peer_name=~\"$service\", http_status_code=\"200\", namespace=\"$namespace\"}[$__rate_interval])",
     "legendFormat": "{{net_peer_name}}"
    }
   ]
  },
  {
   "title": "LLM Token Latencies (GMConnector)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 }
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 63 },
   "options": {
    "content": " **Note:** The diagram illustrates the latency breakdown and the meaning of each metric:\n```\n[Embed] -> [Retrieve] -> [Rerank] -> [                   LLM                   ]\n|<---- Pre-LLM Pipeline Latency ---->|<-------- LLM All Tokens Latency ------->|\n                                     |<- LLM TTFT ->|<- TPOT -><- TPOT ->< .. >|\n|<----------- E2E Time To First Token (TTFT) ------>|\n|<------------------------ E2E Pipeline Latency ------------------------------>|\n\n```"
   }
  },
  {
   "title": "E2E Time To First Token (E2E TTFT)",
   "type": "heatmap",
   "description": "The time from the start of the pipeline until the first token is generated by the LLM., combining pre-LLM stages and LLM Time to First Token.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "sum(increase( router_e2e_ttft_latency_milliseconds_bucket{namespace=\"$namespace\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LLM Time To  First Token (LLM TTFT)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "targets": [
    {
     "expr": "sum(increase( router_llm_first_token_latency_milliseconds_bucket{namespace=\"$namespace\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "E2E Pipeline Latency",
   "type": "heatmap",
   "description": "Displays the execution time distribution for the end-to-end pipeline, with pre-LLM stages (embedding, retrieval, reranking, etc.) along with the LLM inference stage.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "sum(increase( router_e2e_latency_milliseconds_bucket{namespace=\"$namespace\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LLM Time Per Output Token (TPOT)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 76 },
   "targets": [
    {
     "expr": "sum(increase( router_llm_next_token_latency_milliseconds_bucket{namespace=\"$namespace\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pre-LLM Pipeline Latency",
   "type": "heatmap",
   "description": "Displays the execution time distribution for the pre-LLM stages of the pipeline (embedding, retrieval, re-ranking, and, if enabled, input guard processing).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "targets": [
    {
     "expr": "sum(increase( router_pipeline_latency_milliseconds_bucket{namespace=\"$namespace\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LLM All Tokens Latency",
   "type": "heatmap",
   "description": "Displays the execution time distribution for the LLM stage of the pipeline. Measures the duration to generate response from the LLM model server with all tokens.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "targets": [
    {
     "expr": "sum(increase( router_llm_all_tokens_latency_milliseconds_bucket{namespace=\"$namespace\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Server services (filter by \"Route\")",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 }
  },
  {
   "title": "GMConnector responses histogram",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 94 },
   "targets": [
    {
     "expr": "sum(increase( http_server_duration_milliseconds_bucket{http_route=~\"$http_route\", http_status_code=~\"$http_status_code\", namespace=\"$namespace\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 7 Router Server Average Latencies Over Range (only http_status=200)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (http_route) ((increase(http_server_duration_milliseconds_sum{http_route=~\"$http_route\", http_status_code=\"200\", namespace=\"$namespace\", job=\"monitoring/router-service\"}[$__rate_interval]) / increase(http_server_duration_milliseconds_count{http_route=~\"$http_route\", http_status_code=\"200\", namespace=\"$namespace\", job=\"monitoring/router-service\"}[$__rate_interval]) >=0) )",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "Router Server Rate Load (code/route) ",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "avg by (http_route, http_status_code) (rate(http_server_duration_milliseconds_count{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "code=[{{http_status_code}}] - {{http_route}}"
    }
   ]
  }
 ]
}