{
 "title": "EnterpriseRAG / Services / Top",
 "description": "Spanmetrics way of demo application view.",
 "tags": [
  "entrag",
  "microservices"
 ],
 "time": { "from": "now-30m", "to": "now-1m" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_service_created{namespace=~\"chatqna|edp|docsum|audio\"},namespace)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "query_result(count by (container)(count_over_time(http_request_duration_seconds_count[$__range])))"
    }
   },
   {
    "name": "handler",
    "query": {
     "query": "query_result(sum (http_request_duration_seconds_count{container=~\"$container\", namespace=\"$namespace\"})  by (handler))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Service Level - Throughput and Latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Top 3x3 - Service Latency - quantile95",
   "type": "gauge",
   "gridPos": { "h": 20, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(7,histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{container=~\"$container\", handler=~\"$handler\", namespace=\"$namespace\"}[$__range])) by (le,container)))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Top 7 Services Mean Rate over Range",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(7,sum by (container) (rate(http_request_duration_seconds_count{container=~\"$container\", handler=~\"$handler\", namespace=\"$namespace\"}[$__range])))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Handler Level - Latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top 3x3 - handler Latency - quantile95",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(7,histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{container=~\"$container\", handler=~\"$handler\", namespace=\"$namespace\"}[$__range])) by (le,handler)))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Top 7 Highest Endpoint Latencies  Mean Over Range ",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(7, sum by (handler,container)(increase(http_request_duration_seconds_sum{container=~\"${container}\", handler=~\"$handler\", namespace=\"$namespace\"}[5m]) / increase(http_request_duration_seconds_count{container=~\"${container}\",handler=~\"$handler\", namespace=\"$namespace\"}[5m\n])))",
     "legendFormat": "{{handler}} [{{container}}]"
    }
   ]
  },
  {
   "title": "Top 7 Latencies Over Range ",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(7,sum by (handler,container)(increase(http_request_duration_seconds_sum{container=~\"$container\", handler=~\"$handler\", namespace=\"$namespace\"}[$__rate_interval]) / increase(http_request_duration_seconds_count{container=~\"$container\", handler=~\"$handler\", namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "[{{container}}]  {{handler}}"
    }
   ]
  }
 ]
}