
---
# Source: torchserve/templates/configmap.yaml
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: torchserve-config
  labels:
    helm.sh/chart: torchserve-0.8.0
    app.kubernetes.io/name: torchserve
    app.kubernetes.io/instance: torchserve
    app.kubernetes.io/version: "cpu-1.5"
    app.kubernetes.io/managed-by: Helm
data:
  http_proxy:  "http://proxy-mu.intel.com:911"
  https_proxy:  "http://proxy-mu.intel.com:912"
  no_proxy:  "localhost,10.55.253.38,v4-k8s-vip,v4-vip-bm-test,.perf,10.55.253.36,.svc,.svc.cluster.local,.pod.cluster.local,10.233.0.0/18,10.165.118.166/21"
---
# Source: torchserve/templates/service.yaml
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: torchserve
  labels:
    helm.sh/chart: torchserve-0.8.0
    app.kubernetes.io/name: torchserve
    app.kubernetes.io/instance: torchserve
    app.kubernetes.io/version: "cpu-1.5"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8090
      targetPort: 8090
      protocol: TCP
      name: torchserve
  selector:
    app.kubernetes.io/name: torchserve
    app.kubernetes.io/instance: torchserve
---
# Source: torchserve/templates/deployment.yaml
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: torchserve
  labels:
    helm.sh/chart: torchserve-0.8.0
    app.kubernetes.io/name: torchserve
    app.kubernetes.io/instance: torchserve
    app.kubernetes.io/version: "cpu-1.5"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: torchserve
      app.kubernetes.io/instance: torchserve
  template:
    metadata:
      labels:
        app.kubernetes.io/name: torchserve
        app.kubernetes.io/instance: torchserve
    spec:
      securityContext:
        {}
      containers:
        - name: torchserve
          envFrom:
            - configMapRef:
                name: torchserve-config
            - configMapRef:
                name: extra-env-config
                optional: true
          securityContext:
            {}
          image: "localhost:5000/test/pl-qna-rag-embedding-torchserve:latest"
          imagePullPolicy: Always
          resources:
          limits:
            cpu: 16
            memory: 32Gi
          volumeMounts:
            - mountPath: /opt/ml/model
              name: model-volume
            - mountPath: /tmp
              name: tmp
          ports:
            - name: http
              containerPort: 8090
              protocol: TCP
          livenessProbe:
            failureThreshold: 24
            httpGet:
              path: ping
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: ping
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          startupProbe:
            failureThreshold: 120
            httpGet:
              path: ping
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: model-volume
          hostPath:
            path: /mnt/opea-models
            type: Directory
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 1Gi
        - name: tmp
          emptyDir: {}
