name: 'Install SSH Key'
description: 'Installs an SSH key, updates config, and cleans up'
inputs:
  key:
    description: 'SSH private key'
    required: true
  name:
    description: 'Filename for the SSH key'
    required: true
  known_hosts:
    description: 'Known hosts file content (optional)'
    required: false
  config:
    description: 'SSH config'
    required: false
    default: ''
  cleanup:
    description: 'Cleanup key after execution'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Install SSH Key
      shell: bash
      run: |
        mkdir -p /etc/ssh/keys
        echo "${{ inputs.key }}" > /etc/ssh/keys/${{ inputs.name }}
        chmod 600 /etc/ssh/keys/${{ inputs.name }}

        if [ -n "${{ inputs.config }}" ]; then
          echo "${{ inputs.config }}" > /etc/ssh/ssh_config.d/ghworkflow.conf
        fi

        if [ -n "${{ inputs.known_hosts }}" ]; then
          echo "${{ inputs.known_hosts }}" >> /etc/ssh/ssh_known_hosts
          chmod 644 /etc/ssh/ssh_known_hosts
        fi

        function cleanup {
          rm -f /etc/ssh/keys/${{ inputs.name }} /etc/ssh/ssh_config.d/ghworkflow.conf
        }

        if [ ${{ inputs.cleanup }} == "true" ]; then trap cleanup EXIT; fi
