---
- name: "app_vector_databases | Uninstall Helm chart"
  kubernetes.core.helm:
    name: "{{ vector_databases_helm_release_name }}"
    namespace: "{{ vector_databases_namespace }}"
    state: absent
    wait: true
    wait_timeout: "300s"

- name: "app_vector_databases | Delete namespace"
  kubernetes.core.k8s:
    state: absent
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ vector_databases_namespace }}"
