name: pull request comment
on:
  issue_comment:
    types: [created]
jobs:
  job01:
    if: ${{ (github.event.issue.pull_request) && (github.event.comment.body == '/test') }}
    runs-on: [ innersource.prod.amr.dind ]
    steps:
    - name: Tell SHA
      run: "echo ${{ github.sha }}"

    - name: Tell event vars
      run: "echo ${{ github.event.issue.number }}"

    - name: Checkout pull request
      uses: actions/checkout@v4
      with:
        ref: refs/pull/${{ github.event.issue.number }}/head
