name: Linter

on:
  pull_request:
    branches: [ main ]

  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: [rag-runner]
    if: |
      (github.event_name == 'pull_request_review' && github.event.review.state != 'commented') ||
      (github.event_name == 'pull_request') || (github.event_name == 'push')

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      - name: Print YAML Lint Config
        run: cat .github/linters/.yaml-lint.yml
      - name: Super-Linter
        uses: super-linter/super-linter/slim@v6.8.0
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_BASH: true
          BASH_SEVERITY: error
          FILTER_REGEX_EXCLUDE: ".*helm/templates/.*.yaml"
          VALIDATE_YAML: true
          VALIDATE_PYTHON_RUFF: true
          VALIDATE_DOCKERFILE_HADOLINT: true
          GITHUB_TOKEN: ${{ secrets.CLN_GH_TOKEN }}
          DEFAULT_BRANCH: main
