name: "Hadolint + Bandit"

on: [push]

jobs:
  hadolint:
    runs-on: [rag-runner]
    name: Hadolint Scan
    container:
      image: cache-registry.caas.intel.com/cache/library/python:slim
    steps:
      - name: Run Hadolint on Dockerfile(s)
        uses: intel-innersource/frameworks.actions.hadolint@v1.3
        with:
          hadolint_format: tty

  bandit:
    runs-on: [rag-runner]
    name: Bandit Scan
    container:
      image: cache-registry.caas.intel.com/cache/library/python:slim
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Run Bandit
        id: bandit
        uses: intel-innersource/frameworks.actions.bandit@v1.3
