name: Unit tests

on:
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    if: ${{ (github.event.repository.visibility == 'public') && (github.repository_owner == 'intel') }}
    name: Unit tests
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    permissions:
      contents: read
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Clean up disk space
      run: |
        sudo rm -rf \
          /usr/lib/mono \
          /usr/local/julia* \
          /usr/local/lib/android \
          /usr/local/lib/node_modules \
          /usr/local/share/chromium \
          /usr/local/share/powershell \
          /usr/share/dotnet \
          /usr/share/swift \
          /opt/google/chrome \
          /opt/microsoft/msedge \
          /opt/microsoft/powershell \
          "$AGENT_TOOLSDIRECTORY"
        df -h /
    - name: Ingestion unit tests
      uses: ./.github/actions/unit-tests
      with:
        test-name: ingestion_unit_tests
    - name: Prompt registry unit tests
      uses: ./.github/actions/unit-tests
      with:
        test-name: prompt_registry_unit_tests
    - name: Retrievers unit tests
      uses: ./.github/actions/unit-tests
      with:
        test-name: retrievers_unit_tests
    - name: Vectorstores unit tests
      uses: ./.github/actions/unit-tests
      with:
        test-name: vectorstores_unit_tests
    - name: Reranks unit tests
      uses: ./.github/actions/unit-tests
      with:
        test-name: reranks_unit_tests
    - name: Embeddings unit tests
      uses: ./.github/actions/unit-tests
      with:
        test-name: embeddings_unit_tests
    - name: Dataprep unit tests
      uses: ./.github/actions/unit-tests
      with:
        test-name: dataprep_unit_tests
    - name: LLMs unit tests
      uses: ./.github/actions/unit-tests
      with:
        test-name: llms_unit_tests
    - name: Guardrails input unit tests
      uses: ./.github/actions/unit-tests
      with:
        test-name: llm_guard_input_guardrail_unit_tests
    - name: Guardrails output unit tests
      uses: ./.github/actions/unit-tests
      with:
        test-name: llm_guard_output_guardrail_unit_tests
